name: Build Samsung Kernel
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android
          sudo apt-get remove -y azure-cli google-chrome-stable firefox microsoft-edge-stable
          sudo apt-get autoremove -y && sudo apt-get clean
          df -h
      
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu bc bison flex libssl-dev make git wget
      
      - name: Build Kernel
        run: |
          echo "Здесь будет магия сборки!"
          # Пока просто создадим файл-заглушку
          mkdir -p out
          echo "Hello from xizyv kernel!" > out/test_kernel.img
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Test-Kernel
          path: out/test_kernel.img
